# Generated by Django 5.0.3 on 2024-03-14 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_first_name', models.CharField(max_length=100)),
                ('customer_last_name', models.CharField(max_length=100)),
                ('customer_employer', models.CharField(max_length=100)),
                ('customer_job_title', models.CharField(max_length=100)),
                ('customer_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('customer_status', models.CharField(max_length=100)),
                ('customer_created', models.DateTimeField(auto_now_add=True)),
                ('customer_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
