# Generated by Django 5.0.3 on 2024-03-15 19:13

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='customer_date_of_birth',
            field=models.DateField(default=datetime.date(2000, 1, 1)),
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_employment_status',
            field=models.CharField(choices=[('A', 'Active'), ('P', 'Parental Leave'), ('L', 'Leaver')], default='A', max_length=1),
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('N', 'Non-binary'), ('O', 'Other'), ('P', 'Prefer not to say')], default='P', max_length=2),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_status',
            field=models.CharField(choices=[('A', 'Active'), ('P', 'Parental Leave'), ('L', 'Leaver')], default='A', max_length=1),
        ),
        migrations.AlterField(
            model_name='customer',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='employment_details',
            fields=[
                ('employment_id', models.AutoField(primary_key=True, serialize=False)),
                ('employment_employer', models.CharField(max_length=100)),
                ('employment_industry', models.CharField(choices=[('IT', 'Information Technology'), ('HC', 'Healthcare'), ('ED', 'Education'), ('FN', 'Finance'), ('RT', 'Retail'), ('OT', 'Other')], default='OT', max_length=2)),
                ('employment_job_title', models.CharField(choices=[('SE', 'Software Engineer'), ('DA', 'Data Analyst'), ('DS', 'Data Scientist'), ('PM', 'Project Manager'), ('WD', 'Web Developer'), ('DN', 'Dentist'), ('DR', 'Doctor'), ('NR', 'Nurse'), ('PH', 'Pharmacist'), ('TE', 'Teacher'), ('PR', 'Professor'), ('CO', 'Counselor'), ('AD', 'Administrator'), ('LI', 'Librarian'), ('FA', 'Financial Analyst'), ('AC', 'Accountant'), ('IB', 'Investment Banker'), ('FAD', 'Financial Advisor'), ('AU', 'Auditor'), ('SA', 'Sales Associate'), ('SM', 'Store Manager'), ('ME', 'Merchandiser'), ('BU', 'Buyer'), ('RA', 'Retail Analyst'), ('OT', 'Other')], default='OT', max_length=3)),
                ('employment_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('employment_pension_status', models.CharField(choices=[('E', 'Enrolled'), ('N', 'Not Enrolled')], default='N', max_length=1)),
                ('employment_created', models.DateTimeField(auto_now_add=True)),
                ('employment_updated', models.DateTimeField(auto_now=True)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.customer')),
            ],
        ),
    ]
