# Generated by Django 5.0.3 on 2024-03-15 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_customer_customer_date_of_birth_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='customer_employer',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='customer_job_title',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='customer_salary',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='customer_status',
        ),
    ]
