# Generated by Django 5.0.3 on 2024-03-15 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_remove_customer_customer_employer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employment_details',
            old_name='customer_id',
            new_name='customer',
        ),
    ]
