# Generated by Django 5.0.3 on 2024-12-15 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_rename_customer_id_employment_details_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_employment_status',
            field=models.CharField(choices=[('Active', 'Active'), ('Parental Leave', 'Parental Leave'), ('Leaver', 'Leaver')], default='Active', max_length=15),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Non-binary', 'Non-binary'), ('Other', 'Other'), ('Prefer not to say', 'Prefer not to say')], default='Prefer not to say', max_length=20),
        ),
        migrations.AlterField(
            model_name='employment_details',
            name='employment_industry',
            field=models.CharField(choices=[('IT', 'Information Technology'), ('Healthcare', 'Healthcare'), ('Education', 'Education'), ('Finance', 'Finance'), ('Retail', 'Retail'), ('Other', 'Other')], default='Other', max_length=10),
        ),
    ]
