name: Django CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'  # Updated Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-django pytest-custom-exit-code
        pip install -r requirements.txt

    - name: Set environment variables
      run: |
        echo "DJANGO_SETTINGS_MODULE=sea.settings" >> $GITHUB_ENV

    - name: Print environment variables
      run: |
        printenv

    - name: Run tests
      run: |
        pytest
